### ISSUE TITLE
database operation builder methods issue

### ISSUE THREAD

**Issue by abusuioc** [SiimKinks/sqlitemagic#1]
Hi, trying out your library's examples, I cannot do a simple insert because apparently the `insert` method is not found in the Book class:

```
@Table(persistAll = true)
@AutoValue
public abstract class Book
```

```
Book book = new Book(77, "Bar", author);

Single<Long> insert = book
    .insert()
    .observe();
```

How can I debug why the database operation builder methods are not "automagically" generated during compile time?

**Comment by SiimKinks** [comment]
It seems that you haven't installed the IntelliJ plugin. Please refer to https://github.com/SiimKinks/sqlitemagic/wiki/Setup#install-intellij-plugin

**Comment by abusuioc** [comment]
You're absolutely right, seems I skipped that paragraph, thank you.
