### ISSUE TITLE
Update sample

### ISSUE THREAD

**Issue by vincent-paing** [SiimKinks/sqlitemagic#12]
The sample is still using the old initialization method, it need to use the new builder pattern

https://github.com/SiimKinks/sqlitemagic/blob/406ffb01959bfd8e3b8449053f8198e9afc2a6df/sqlitemagic-sample/app/src/main/java/com/siimkinks/sqlitemagic/sample/SampleApp.java#L11

**Comment by SiimKinks** [comment]
Sample app updated in https://github.com/SiimKinks/sqlitemagic/commit/498a10000a46ef4ab9fe43f2208a2696a1178695
