### ISSUE TITLE
UpdateBuilder does not work when passing value directly

### ISSUE THREAD

**Issue by vincent-paing** [SiimKinks/sqlitemagic#14]
Here's the reproducible code

```java
@Table(persistAll = true)
public class Entity {

  @Id(autoIncrement = true) public Long id;

  public Boolean isSomething;
}
```

And updating `isSomething` column  with following code

``` java  
 Update.table(EntityTable.ENTITY)
        .set(EntityTable.ENTITY.IS_SOMETHING, true)
        .execute();
```

This should translate to

```sql
UPDATE TABLE entity SET isSomething = true
```

However, the code does not compile because it cannot resolve method, since it does not know the method where you pass the value instead of Column..etc.

![image](https://user-images.githubusercontent.com/8557241/49126548-5b25a000-f2f2-11e8-9f98-44ae0a12d2cd.png)

Tested on version 0.23.1

**Comment by SiimKinks** [comment]
The updatable column `public Boolean isSomething` is nullable (since there is missing @NonNull/@NotNull annotation). To keep things very explicit and clear SqliteMagic is trying to make API consumers aware of nullability. Therefore there is a method `setNullable` which will work in your case.
