### ISSUE TITLE
Facing issue in getdbversion even after gradle build is succeded.

### ISSUE THREAD

**Issue by rakeshfern** [SiimKinks/sqlitemagic#18]
Can you please let us know how to resolve as  this package is not working suddenly on few of the machines from august 2024 facing database initilisation error.

**Comment by SiimKinks** [comment]
If you say it "is not working suddenly on few of the machines from august" then what changed in your configuration?

**Comment by rakeshfern** [comment]
No Configuration been changed.Is this could be the reason,because we are using it from jitpack.io

https://jfrog.com/blog/jcenter-sunset/

**Comment by rakeshfern** [comment]
![image](https://github.com/user-attachments/assets/b456cc00-a5c6-4fe3-a286-1969a4746ed2)

Created this folders locally with respective jar files in it and even referred this folders directly in project it fails.

**Comment by rakeshfern** [comment]
![image](https://github.com/user-attachments/assets/b2ef642f-f4de-4723-be3b-20cd454168da)

All the builds in the jitpack.io is failed can you please look into it and help on this @SiimKinks ?
