### ISSUE TITLE
What could it be the issue here, as I'm only receiving one specific device with issue & it happens when querying a single row. 

### ISSUE THREAD

**Issue by k0shk0sh** [SiimKinks/sqlitemagic#3]
```
Exception java.lang.IllegalStateException: newPosition should be in the window at this point

android.database.sqlite.SQLiteCursor.onMove (SQLiteCursor.java:133)



```

**Comment by SiimKinks** [comment]
Can you please provide more info?
OS version, device name, exact query or code that produces the problem, longer stacktrace, etc.
Not much I can say from provided info currently.

**Comment by k0shk0sh** [comment]
Sorry about that, I did created the issue  & was abit in a rush. 

Here is a long version of the stack

```
android.database.sqlite.SQLiteCursor.onMove (SQLiteCursor.java:133)
bvl.a (SourceFile:126)
bvl.moveToFirst (SourceFile:83)
bye.a (SourceFile:145)
bwj.a (SourceFile:104)
bwj.b (SourceFile:18)
buw$b.b (SourceFile:321)
buw$b.a (SourceFile:334)
com.fastaccess.data.dao.LoginModel.getUser (SourceFile:69)
com.fastaccess.provider.tasks.NotificationJobTask.a (SourceFile:41)
ake.a (SourceFile:107)
ajt$a.onServiceConnected (SourceFile:164)
android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1453)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1481)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6169)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:888)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:778)
```

The line that has the query: 

[LoginModel](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/data/dao/LoginModel.java#L64) and [NotificationJobTask](https://github.com/k0shk0sh/FastHub/blob/master/app/src/main/java/com/fastaccess/provider/tasks/NotificationJobTask.java#L41l)

the Device

```
Manufacturer: LGE
Model: Nexus 5
Board: Hammerhead
Android API: 25
Android OS: 7.1.1
Brand: Google
RAM: 1.81GB
Orientation: Portrait

```

P.S: the user has 7 instances of this impact.

**Comment by k0shk0sh** [comment]
P.S: the user has 7 instances of this impact.

**Comment by k0shk0sh** [comment]
In a second thought, after reading some discussion online, it seems like its more like a rom bug rather than the library & I don't think its either the library or my app responsibility to spend more time fixing something for only a specific rom*. 

I'm going to close this issue & sorry for buzzing you.

**Comment by SiimKinks** [comment]
No problem.
One sidenote - I saw your model had `@Column` for each column field and also had the `@Table(persistAll = true)`. Thanks to the `persistAll = true` parameter, all the `@Column` annotations are unnecessary (please refer to the [first section in this wiki page](https://github.com/SiimKinks/sqlitemagic/wiki/Defining-Database-Schema)).
Also, if you statically import table constants (e.g. `LOGIN_MODEL`) you can make your code look cleaner and shorter.

**Comment by k0shk0sh** [comment]
Thanks tho for your suggestion, I guess i missed that one(`@Colum`) & static import for LOGIN_MODEL, if you look at the other classes you'll fine that i'm doing that over and over again, but i guess I'll clean it later today.

I will be really happy if you could have a closer on the dao package in general since it contains all of the Tables, maybe there are some stuff that i'm doing wrong or you might have batter way of doing it, i'm all listening. 

Thanks again.
