### ISSUE TITLE
question for SQLITE_SEQUENCE

### ISSUE THREAD

**Issue by IvanGarza07** [SiimKinks/sqlitemagic#4]
how can i reset the SQLITE_SEQUENCE with sqlite magic. do sqlite magic have a way to run or exec a query like that db.execSQL("DELETE FROM sqlite_sequence WHERE name= TABLE_NAME");

**Comment by SiimKinks** [comment]
Currently running a raw SQL like that is not supported. It will definitely be implemented in some future version. Until then all proposals on implementation details are welcome.

**Comment by IvanGarza07** [comment]
Ok thank you for your info! I'll be waiting for the next update, the library its so useful

**Comment by SiimKinks** [comment]
Starting from version 0.17.0 it is possible to execute raw DELETE and UPDATE statements using corresponding operation builders.
