### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by msadeghifard1989** [SiimKinks/sqlitemagic#5]
![untitled](https://user-images.githubusercontent.com/6435941/27457464-1bcd01d4-57ba-11e7-841d-8586cf9f3947.png)
   

apply plugin: 'com.android.application'
apply plugin: 'com.siimkinks.sqlitemagic'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
        classpath 'com.siimkinks.sqlitemagic:sqlitemagic-plugin:0.12.0'
    }
}

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "ms.nakon.foozool.app1"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        buildConfigField "int", "DB_VERSION", "1"
        // Optional (defaults to "database.db")
        buildConfigField "String", "DB_NAME", '"sample.db"'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.github.florent37:materialviewpager:1.2.1'
    //dependencies
    compile 'com.flaviofaria:kenburnsview:1.0.7'
    compile 'com.jpardogo.materialtabstrip:library:1.1.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.jakewharton:butterknife:8.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.1.0'
    compile 'com.android.support:cardview-v7:+'

}

**Comment by SiimKinks** [comment]
You are missing RxJava2 dependency
