### ISSUE TITLE
Transfromer annotation is deprecated not updated in Wiki

### ISSUE THREAD

**Issue by vincent-paing** [SiimKinks/sqlitemagic#7]
Although Transformer is marked as deprecated. The wiki still shows an example using Transformer. What's the alternative without using it?

**Comment by SiimKinks** [comment]
New way of using it, is just not to annotate any classes with `@Transformer` annotations.
Also updated the wiki: [Object Transformers](https://github.com/SiimKinks/sqlitemagic/wiki/Object-Transformers)
